clemente-lab/mmeds-meta

README.md, mmeds/config.py, mmeds/mmeds.py, mmeds/resources/job_template.lsf, mmeds/tools.py, sql/users.sql
=> Tweaked a few things for Minerva

README.md, mmeds/resources/summary_code.txt, mmeds/summarize.py, mmeds/tools.py
mmeds/resources/summary_code.txt: Updated code for manipulating qiime2 results
mmeds/tools.py: Fixed issues. Modified Qiime2.summarize() to collect the right files.
mmeds/summarize.py: Made some minor changes to make the main function compatible with both Qiime 1 & 2
Use the web interface to run qiime2 analysis on a dataset. The owner of the data will receive
an email with a PDF of graphs of the analysis results.
In summarize.py, summarize_qiime1() is now summarize() and is generalizable between
qiime 1 & 2 based on the analysis_type parameter.
Many of the changes are formatting or a function getting an additional parameter so it's not as bad as it looks.
=> Finished summary for Qiime2

.coveragerc, .gitignore, .travis.yml, README.md, mmeds/authentication.py, mmeds/config.py, mmeds/database.py, mmeds/qiime1.py, mmeds/tests/test_authentication.py, mmeds/tests/test_qiime.py, mmeds/tests/test_tool.py, mmeds/tool.py
=> Test tools

README.md, mmeds/config.py, mmeds/error.py, mmeds/mmeds.py, mmeds/resources/summary_code.txt, mmeds/spawn.py, mmeds/summary.py, mmeds/test_files/test_config_file_fail1.txt, mmeds/test_files/test_config_file_fail2.txt, mmeds/test_files/test_config_file_fail3.txt, mmeds/tests/test_mmeds.py, mmeds/tests/test_qiime.py, mmeds/tests/test_tool.py, mmeds/tool.py, server/server.py
There are many files changed for this but most are just due to updates to the tests. The other files are
- __mmeds/config.py__: Added a list of the parameters in the analysis config file. Any new parameters added must be added to the list.
- __mmeds/error.py__: Added a new error (InvalidConfigError) for any issues in the config file.
- __mmeds/mmeds.py__: Updated load_config and get_valid_columns to raise an InvalidConfigError if there are issues in the config file. Updated the functions to work off of a MMEDS metadata file rather than a qiime mapping file.
- __mmeds/spawn.py__: Updated spawn_analysis to handle new load_config parameters.
- __mmeds/summary.py__: Updated so that the metadata file is included in the summary as well as the mapping file.
- __mmeds/tool.py__: Added a method …
=> Added checks to analysis config file

README.md, mmeds/qiime1.py, mmeds/qiime2.py, mmeds/tool.py
Finally a (relatively) small pull request. Basically I updated the jobfiles to use environment variables for the directory the analysis is run in. 
mmeds/tool.py: Added Tool class property `self.run_dir` that is a environment variable defined in the
jobfile for each tool. Added method `get_file` for returning the path to a file using the `self.run_dir` variable.
mmeds/qiime1.py: Updated many methods to use `self.get_file` method
mmeds/qiime2.py: Updated many methods to use `self.get_file` method
=> Switch the qiime tools to use paths relative to environment variables

mmeds/validate.py
=> Enhancement additional validation

mmeds/CSS/stylesheet.css, mmeds/config.py, mmeds/database.py, mmeds/html/analysis_query.html, mmeds/html/blank.html, mmeds/server.py, mmeds/tests/server/test_server.py, mmeds/tests/unit/test_database.py, mmeds/util.py
mmeds/CSS/stylesheet.css: Increased padding so query results don't overlap the side bar
mmeds/config.py: Add additional html pages.
mmeds/database.py: Updated Database.execute to automatically prepend 'protected_' to protected table queries
mmeds/server.py: re-added page for executing SQL queries
=> Testing server sql query

README.md, mmeds/error.py, mmeds/log.py, mmeds/tests/server/test_server.py, mmeds/tool.py, mmeds/util.py, setup.py
Added a MMEDSLog class to perform setup and calls to the Python Logger class.
Added error logs everytime a MMEDSError is raised.
Modified `mmeds/util.py:log` to pass log messages to a MMEDSlog instance
=> Enhancement proper logging

mmeds/database.py, mmeds/documents.py, mmeds/html/download_selected_analysis.html, mmeds/html/download_selected_study.html, mmeds/qiime1.py, mmeds/qiime2.py, mmeds/server.py, mmeds/spawn.py, mmeds/tests/unit/test_documents.py, mmeds/tool.py, mmeds/util.py
Combined the AnalysisDoc and StudyDoc classes into a single MMEDSDoc class. This will facilitate running analyses using results from prior analysis and input data
=> Enhancement combine documents

mmeds/config.py, mmeds/database.py, mmeds/documents.py, mmeds/lefse.py, mmeds/qiime1.py, mmeds/qiime2.py, mmeds/resources/config_file.yaml, mmeds/server.py, mmeds/sparcc.py, mmeds/spawn.py, mmeds/test_files/sub_config_file.yaml, mmeds/test_files/test_config_all.yaml, mmeds/test_files/test_config_file.yaml, mmeds/test_files/test_config_file_fail3.yaml, mmeds/tests/unit/test_tool.py, mmeds/tests/unit/test_tools.py, mmeds/tool.py
I added a queue property to the Tool class and sub-classes so they can pass info on new processes to create back to the watcher.
Moved functions in spawn.py into the Watcher class as methods
=> Enhancement watcher babies

mmeds/authentication.py, mmeds/config.py, mmeds/error.py, mmeds/server.py, mmeds/spawn.py, mmeds/tests/integration/test_analysis.py, mmeds/tests/server/test_server.py, mmeds/tools/qiime2.py, mmeds/tools/tool.py, mmeds/util.py
Closes #200 #201 #203 #204 
A bunch of little things related to getting functionality working on Minerva again. Updated `test_analysis.py` to work with the new queue setup. Fixed email formatting so the analysis name will be properly included. Updated `mmeds_to_qiime_metadata` to use the proper doc property.
=> Enhancement migrate to hydra

mmeds/config.py, mmeds/database.py, mmeds/server.py, mmeds/tools/tool.py, mmeds/validate.py, test_files/test_subject.tsv
closes #197 #154 
Adding mutliprocess logging import in a few places to address multiple log outputs. Proper PR for logging is on the todo.
Removed automatic handling of all KeyErrors, it was never a good idea.
Updated validation to properly handle AdditionalMetaData and type information in the subject metadata file.
=> Bug fix unhandled upload error

mmeds/app.wsgi, mmeds/database.py, mmeds/log.py, mmeds/spawn.py, mmeds/tools/tool.py
Should've had this in the original PR for WSGI. Code review programs will be made about imports not being at the top level but this is necessary since the tests will fail with `multiprocessing.dummy` (faking the process api using threads) but real processes can't run on web services, at least for now.
=> simple fixes

mmeds/config.py, mmeds/database/database.py, mmeds/error.py, mmeds/html/analysis_view_page.html, mmeds/resources/log_config.yaml, mmeds/server.py, mmeds/spawn.py, mmeds/tests/unit/test_util.py, mmeds/tools/qiime1.py, mmeds/tools/qiime2.py, mmeds/tools/tool.py, mmeds/util.py, summary_old.py, www_files/app.py, www_files/htaccess
Addresses most of the small issues found during the MMEDS demo on 2020-1-19
- Server now gives an error if the config file has issues before passing it to the watcher
- Server now gives a missing upload error when requesting analysis
- Server now Gives user an error if the study name includes non-alphanumeric characters or is already in use
- Fixed some typos
mmeds/database/database.py + mmeds/error.py: Added methods/errors for new checks
mmeds/server.py: Added functionality to catch issues before they get to the watcher
Example: To do X run new function Y with parameters A, B, and C …
=> Minor demo fixes

.gitignore, mmeds/database/database.py, mmeds/formatter.py, mmeds/secrets.py, mmeds/tests/server/test_server.py, mmeds/tests/unit/test_database.py, mmeds/util.py, www_files/app.py
Fixes the SQL issues on Minerva.
Most of the changes are adding backticks to places they previously weren't
the SQL fix is in database.py: `def execute`
=> Bug fix minerva sql

mmeds/config.py, mmeds/database/database.py, mmeds/database/metadata_adder.py, mmeds/html/upload_select_page.html, mmeds/server.py, mmeds/spawn.py, mmeds/tests/server/test_server.py, mmeds/tests/unit/test_adder.py, mmeds/tests/unit/test_database.py, mmeds/tests/unit/test_spawn.py, mmeds/validate.py, test_files/test_add_aliquot.tsv, test_files/test_add_sample.tsv
Closes #276 
`mmeds/database/database.py`: Modified generate_*_id functions to refrain from generating an ID when one is passed in. Added parameter `generate_id` to multiple locations to control this.
`mmeds/html/upload_select_page.html`: Merged AddData and GTenerateID forms into a single form.
`mmeds/server.py`: merged generate_multiple_ids and additional_metadata into a single method.
=> Upload existing i ds

scripts/generate_test_tsv.py
generate_test_tsv.py created and completed.
Run python file with argument -p Path to test files
Design based on generate_test_metadata.py and has largely not changed structure
'Other' values are given as dicts of {boolean: boolean}
Number values are integers between 1 and 2000
Date values are YYYY-MM-DD between 2015 and 2025
DD values do not go above 28
=> Step 1 complete.

mmeds/html/upload_data_files.html, mmeds/html/upload_select_page.html, mmeds/server.py, mmeds/tests/server/test_server.py, mmeds/tests/server/test_server_generated.py
Removed upload type selection from initial upload page. Moved to collapsible divs on the final upload page, in the same style as the choice between starting a new upload and adding to an existing upload.
-   [x] Is the code tested?
=> Enhancement move data type

docs/summary_env_new.md, mmeds/config.py, mmeds/tools/tool.py
changes to tool.py to reflect summary improvements
config.py sorting out pathing, logic for connecting to databases to work in different situations: 
on minerva and on web01, on minerva and not web01, not on minerva and run through github actions. 
Tested with short_study in mmeds-meta/test_files
=> summaries working in production

.github/workflows/tests.yml, conda_env_files/jupyter_env.yaml, mmeds/config.py, mmeds/database/database.py, mmeds/database/documents.py, mmeds/html/analysis_select_tool.html, mmeds/resources/cutie_config.yaml, mmeds/resources/cutie_config_template.ini, mmeds/resources/lefse_config.yaml, mmeds/resources/picrust2_config.yaml, mmeds/resources/sparcc_config.yaml, mmeds/resources/summary_code.txt, mmeds/server.py, mmeds/spawn.py, mmeds/summary.py, mmeds/tests/server/test_server.py, mmeds/tests/unit/test_documents.py, mmeds/tests/unit/test_tool.py, mmeds/tests/unit/test_tools.py, mmeds/tests/unit/test_util.py, mmeds/tools/cutie.py, mmeds/tools/lefse.py, mmeds/tools/picrust2.py, mmeds/tools/qiime2.py, mmeds/tools/sparcc.py, mmeds/tools/tool.py, mmeds/util.py, scripts/format_lefse.py, scripts/run_analysis.py
Four new analysis tools have been added: CUTIE, SparCC, PiCRUSt2, and LeFSe. There has also been various improvements to analyses in general, allowing for files to be used between different tools, more specific config files, and being able to run analyses from the command line. Code coverage is also significantly improved, with analysis tools being reintroduced in the testing framework.
To run an analysis manually use the `run_analysis.py` script in a mmeds environment. View this script's `--help` for details. Alternatively, these tools are available as normal in the web UI. web01 is only partially up though, so the jobs need to be manually submitted on another node once they're …
=> Enhancement adding analysis tools
